### ISSUE TITLE
is it possible to print simple tables separated by space?

### ISSUE THREAD

**Issue by srghma** [natefaubion/purescript-dodo-printer#7]
```
text     text text
texttext text texttext
```

**Comment by srghma** [comment]
no https://github.com/quchen/prettyprinter/issues/53

**Comment by srghma** [comment]
basically I would like to have something like this

https://user-images.githubusercontent.com/7573215/152129507-4a20dd26-3ae3-4c55-bfc4-3b383be305cd.png

**Comment by natefaubion** [comment]
It would be non-trivial to support in a first class way. Like the linked ticket says, wadler/leijen style printing is not a general-purpose layout algorithm. `dodo` has experimental support for local overrides https://github.com/natefaubion/purescript-dodo-printer/blob/540dba0442abe686c0b211868d6f423e5df81b69/src/Dodo.purs#L197-L200 and also some context sensitivity https://github.com/natefaubion/purescript-dodo-printer/blob/540dba0442abe686c0b211868d6f423e5df81b69/src/Dodo.purs#L97-L99 so in theory something might be possible. The difficult part is aligning things next to each other. You would probably have to completely bake the nested documents, split them on lines, and zip them back together. Doc annotations (like for ANSI colors) are handled in the renderer, and layout decisions are done dynamically while printing, so there's no current way to layout a `Doc` and get a `Doc` back. You could potentially write a `Doc` printer, that is, a printer that prints Docs back into `Doc`, or in some other intermediate boxes-like structure that you can manipulate back into the expected form.

**Comment by natefaubion** [comment]
> You could potentially write a Doc printer, that is, a printer that prints Docs back into Doc, or in some other intermediate boxes-like structure that you can manipulate back into the expected form.

I've run some experiments, and I think this will work as long as you assume annotations are distributive. I'll try to tighten my implementation up over the next few days.

**Comment by natefaubion** [comment]
As an example, here it is working with ansi graphics:
<img width="744" alt="Screen Shot 2022-02-05 at 1 18 30 PM" src="https://user-images.githubusercontent.com/144058/152659450-a707e838-96b8-45cf-9165-75ff3469bec3.png">

With some high-level code:
```purescript
test :: Doc GraphicsParam
test = Box.toDoc do
  let
    a =
      heading
        (textBox 40 (Ansi.bold $ Dodo.text "Heading 1"))
        (textBox 40 (Ansi.italic para1))
    b =
      heading
        (textBox 60 (Ansi.bold $ Dodo.text "Heading 2"))
        (textBox 60 (Ansi.foreground Ansi.Yellow para1))

  a `hgutter 3` b
```
